/*
 *  Generated by https://github.com/killbill/api-pojos. Do not edit!
 *
 *  Copyright 2022-2022 The Billing Project, LLC
 *
 *  The Billing Project licenses this file to you under the Apache License,
 *  version 2.0 (the "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 */

package org.killbill.billing.control.plugin.api.boilerplate.plugin;

import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.util.StdDateFormat;
import com.fasterxml.jackson.datatype.joda.JodaModule;
import java.io.IOException;
import org.killbill.billing.control.plugin.api.PaymentControlContext;
import org.testng.Assert;
import org.testng.annotations.Test;


@Test(groups = { "fast" })
public class PaymentControlContextImpTest {
    @Test
    public void anInstanceShouldBeEqualToItself()
    {
      PaymentControlContextImp a = new PaymentControlContextImp.Builder<>().build();
      Assert.assertTrue(a.equals(a));
    }
    @Test
    public void anInstanceShouldBeEqualToItsCopy()
    {
      PaymentControlContextImp a = new PaymentControlContextImp.Builder<>().build();
      PaymentControlContextImp b = new PaymentControlContextImp(a);

      Assert.assertTrue(a.equals(b));
    }
    @Test
    public void twoNewInstancesShouldBeEqual()
    {
      PaymentControlContextImp a = new PaymentControlContextImp.Builder<>().build();
      PaymentControlContextImp b = new PaymentControlContextImp.Builder<>().build();

      Assert.assertTrue(a.equals( b));
    }
    @Test
    public void twoNewInstancesHashcodeShouldBeEqual()
    {
      PaymentControlContextImp a =  new PaymentControlContextImp.Builder<>().build();
      PaymentControlContextImp b =  new PaymentControlContextImp.Builder<>().build();

      Assert.assertTrue(a.hashCode() == b.hashCode());
    }
    @Test
    public void twoNewInstancesStringShouldBeEqual()
    {
      PaymentControlContextImp a =  new PaymentControlContextImp.Builder<>().build();
      PaymentControlContextImp b =  new PaymentControlContextImp.Builder<>().build();

      Assert.assertTrue(a.toString().equals(b.toString()));
    }
    @Test
    public void callIssers()
    {
      PaymentControlContextImp a =  new PaymentControlContextImp.Builder<>().build();

      a.isApiPayment();
    }
    @Test
    public void callGetters()
    {
      PaymentControlContextImp a =  new PaymentControlContextImp.Builder<>().build();

      a.getAccountId();
      a.getAmount();
      a.getAttemptPaymentId();
      a.getCallOrigin();
      a.getComments();
      a.getCreatedDate();
      a.getCurrency();
      a.getHPPType();
      a.getPaymentApiType();
      a.getPaymentExternalKey();
      a.getPaymentId();
      a.getPaymentMethodId();
      a.getPaymentPluginName();
      a.getProcessedAmount();
      a.getProcessedCurrency();
      a.getReasonCode();
      a.getTenantId();
      a.getTransactionExternalKey();
      a.getTransactionId();
      a.getTransactionType();
      a.getUpdatedDate();
      a.getUserName();
      a.getUserToken();
      a.getUserType();
    }
    @Test
    public void jsonRoundtrip()
      throws IOException,
        JsonParseException,
        JsonProcessingException,
        JsonMappingException
    {
      ObjectMapper mapper = new ObjectMapper();
      mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
      mapper.registerModule(new JodaModule());
      mapper.setDateFormat(new StdDateFormat().withColonInTimeZone(true));
      mapper.findAndRegisterModules();

      PaymentControlContextImp a =  new PaymentControlContextImp.Builder<>().build();
      String s =  mapper.writeValueAsString(a);;
      PaymentControlContext b = mapper.readValue(s, PaymentControlContext.class);

      Assert.assertTrue(a.equals( b));
    }
}
