/*
 *  Generated by https://github.com/killbill/api-pojos. Do not edit!
 *
 *  Copyright 2022-2022 The Billing Project, LLC
 *
 *  The Billing Project licenses this file to you under the Apache License,
 *  version 2.0 (the "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 */

package org.killbill.billing.control.plugin.api.boilerplate;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.Objects;
import org.joda.time.DateTime;
import org.killbill.billing.control.plugin.api.OnFailurePaymentControlResult;
import org.killbill.billing.payment.api.PluginProperty;

@JsonDeserialize( builder = OnFailurePaymentControlResultImp.Builder.class )
public class OnFailurePaymentControlResultImp implements OnFailurePaymentControlResult {

    protected Iterable<PluginProperty> adjustedPluginProperties;
    protected DateTime nextRetryDate;

    public OnFailurePaymentControlResultImp(final OnFailurePaymentControlResultImp that) {
        this.adjustedPluginProperties = that.adjustedPluginProperties;
        this.nextRetryDate = that.nextRetryDate;
    }
    protected OnFailurePaymentControlResultImp(final OnFailurePaymentControlResultImp.Builder<?> builder) {
        this.adjustedPluginProperties = builder.adjustedPluginProperties;
        this.nextRetryDate = builder.nextRetryDate;
    }
    protected OnFailurePaymentControlResultImp() { }
    @Override
    public Iterable<PluginProperty> getAdjustedPluginProperties() {
        return this.adjustedPluginProperties;
    }
    @Override
    public DateTime getNextRetryDate() {
        return this.nextRetryDate;
    }
    @Override
    public boolean equals(final Object o) {
        if ( this == o ) {
            return true;
        }
        if ( ( o == null ) || ( this.getClass() != o.getClass() ) ) {
            return false;
        }
        final OnFailurePaymentControlResultImp that = (OnFailurePaymentControlResultImp) o;
        if( !Objects.equals(this.adjustedPluginProperties, that.adjustedPluginProperties) ) {
            return false;
        }
        if( ( this.nextRetryDate != null ) ? ( 0 != this.nextRetryDate.compareTo(that.nextRetryDate) ) : ( that.nextRetryDate != null ) ) {
            return false;
        }
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        result = ( 31 * result ) + Objects.hashCode(this.adjustedPluginProperties);
        result = ( 31 * result ) + Objects.hashCode(this.nextRetryDate);
        return result;
    }
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer(this.getClass().getSimpleName());
        sb.append("{");
        sb.append("adjustedPluginProperties=").append(this.adjustedPluginProperties);
        sb.append(", ");
        sb.append("nextRetryDate=").append(this.nextRetryDate);
        sb.append("}");
        return sb.toString();
    }

    @SuppressWarnings("unchecked")
    public static class Builder<T extends OnFailurePaymentControlResultImp.Builder<T>> {

        protected Iterable<PluginProperty> adjustedPluginProperties;
        protected DateTime nextRetryDate;

        public Builder() { }
        public Builder(final Builder that) {
            this.adjustedPluginProperties = that.adjustedPluginProperties;
            this.nextRetryDate = that.nextRetryDate;
        }
        public T withAdjustedPluginProperties(final Iterable<PluginProperty> adjustedPluginProperties) {
            this.adjustedPluginProperties = adjustedPluginProperties;
            return (T) this;
        }
        public T withNextRetryDate(final DateTime nextRetryDate) {
            this.nextRetryDate = nextRetryDate;
            return (T) this;
        }
        public T source(final OnFailurePaymentControlResult that) {
            this.adjustedPluginProperties = that.getAdjustedPluginProperties();
            this.nextRetryDate = that.getNextRetryDate();
            return (T) this;
        }
        protected Builder validate() {
          return this;
        }
        public OnFailurePaymentControlResultImp build() {
            return new OnFailurePaymentControlResultImp(this.validate());
        }
    }
}
