/*
 *  Generated by https://github.com/killbill/api-pojos. Do not edit!
 *
 *  Copyright 2022-2022 The Billing Project, LLC
 *
 *  The Billing Project licenses this file to you under the Apache License,
 *  version 2.0 (the "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 */

package org.killbill.billing.entitlement.api.boilerplate;

import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.util.StdDateFormat;
import com.fasterxml.jackson.datatype.joda.JodaModule;
import java.io.IOException;
import org.killbill.billing.entitlement.api.Subscription;
import org.testng.Assert;
import org.testng.annotations.Test;


@Test(groups = { "fast" })
public class SubscriptionImpTest {
    @Test
    public void anInstanceShouldBeEqualToItself()
    {
      SubscriptionImp a = new SubscriptionImp.Builder<>().build();
      Assert.assertTrue(a.equals(a));
    }
    @Test
    public void anInstanceShouldBeEqualToItsCopy()
    {
      SubscriptionImp a = new SubscriptionImp.Builder<>().build();
      SubscriptionImp b = new SubscriptionImp(a);

      Assert.assertTrue(a.equals(b));
    }
    @Test
    public void twoNewInstancesShouldBeEqual()
    {
      SubscriptionImp a = new SubscriptionImp.Builder<>().build();
      SubscriptionImp b = new SubscriptionImp.Builder<>().build();

      Assert.assertTrue(a.equals( b));
    }
    @Test
    public void twoNewInstancesHashcodeShouldBeEqual()
    {
      SubscriptionImp a =  new SubscriptionImp.Builder<>().build();
      SubscriptionImp b =  new SubscriptionImp.Builder<>().build();

      Assert.assertTrue(a.hashCode() == b.hashCode());
    }
    @Test
    public void twoNewInstancesStringShouldBeEqual()
    {
      SubscriptionImp a =  new SubscriptionImp.Builder<>().build();
      SubscriptionImp b =  new SubscriptionImp.Builder<>().build();

      Assert.assertTrue(a.toString().equals(b.toString()));
    }
    @Test
    public void callIssers()
    {
      SubscriptionImp a =  new SubscriptionImp.Builder<>().build();

    }
    @Test
    public void callGetters()
    {
      SubscriptionImp a =  new SubscriptionImp.Builder<>().build();

      a.getAccountId();
      a.getBaseEntitlementId();
      a.getBillCycleDayLocal();
      a.getBillingEndDate();
      a.getBillingStartDate();
      a.getBundleExternalKey();
      a.getBundleId();
      a.getChargedThroughDate();
      a.getCreatedDate();
      a.getEffectiveEndDate();
      a.getEffectiveStartDate();
      a.getExternalKey();
      a.getId();
      a.getLastActivePhase();
      a.getLastActivePlan();
      a.getLastActivePriceList();
      a.getLastActiveProduct();
      a.getLastActiveProductCategory();
      a.getQuantity();
      a.getSourceType();
      a.getState();
      a.getSubscriptionEvents();
      a.getUpdatedDate();
    }
    @Test
    public void jsonRoundtrip()
      throws IOException,
        JsonParseException,
        JsonProcessingException,
        JsonMappingException
    {
      ObjectMapper mapper = new ObjectMapper();
      mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
      mapper.registerModule(new JodaModule());
      mapper.setDateFormat(new StdDateFormat().withColonInTimeZone(true));
      mapper.findAndRegisterModules();

      SubscriptionImp a =  new SubscriptionImp.Builder<>().build();
      String s =  mapper.writeValueAsString(a);;
      Subscription b = mapper.readValue(s, Subscription.class);

      Assert.assertTrue(a.equals( b));
    }
}
