/*
 *  Generated by https://github.com/killbill/api-pojos. Do not edit!
 *
 *  Copyright 2022-2022 The Billing Project, LLC
 *
 *  The Billing Project licenses this file to you under the Apache License,
 *  version 2.0 (the "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 */

package org.killbill.billing.usage.plugin.api.boilerplate;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import org.joda.time.DateTime;
import org.killbill.billing.payment.api.PluginProperty;
import org.killbill.billing.usage.api.RawUsageRecord;
import org.killbill.billing.usage.plugin.api.UsageContext;
import org.killbill.billing.usage.plugin.api.UsagePluginApi;

@JsonDeserialize( builder = UsagePluginApiImp.Builder.class )
public class UsagePluginApiImp implements UsagePluginApi {


    public UsagePluginApiImp(final UsagePluginApiImp that) {
    }
    protected UsagePluginApiImp(final UsagePluginApiImp.Builder<?> builder) {
    }
    protected UsagePluginApiImp() { }
    @Override
    public List<RawUsageRecord> getUsageForAccount(final DateTime startDate, final DateTime endDate, final UsageContext context, final Iterable<PluginProperty> properties) {
        throw new UnsupportedOperationException("getUsageForAccount(org.joda.time.DateTime, org.joda.time.DateTime, org.killbill.billing.usage.plugin.api.UsageContext, java.lang.Iterable<org.killbill.billing.payment.api.PluginProperty>) must be implemented.");
    }
    @Override
    public List<RawUsageRecord> getUsageForSubscription(final UUID subscriptionId, final DateTime startDate, final DateTime endDate, final UsageContext context, final Iterable<PluginProperty> properties) {
        throw new UnsupportedOperationException("getUsageForSubscription(java.util.UUID, org.joda.time.DateTime, org.joda.time.DateTime, org.killbill.billing.usage.plugin.api.UsageContext, java.lang.Iterable<org.killbill.billing.payment.api.PluginProperty>) must be implemented.");
    }
    @Override
    public boolean equals(final Object o) {
        if ( this == o ) {
            return true;
        }
        if ( ( o == null ) || ( this.getClass() != o.getClass() ) ) {
            return false;
        }
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        return result;
    }
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer(this.getClass().getSimpleName());
        sb.append("{");
        sb.append("}");
        return sb.toString();
    }

    @SuppressWarnings("unchecked")
    public static class Builder<T extends UsagePluginApiImp.Builder<T>> {


        public Builder() { }
        public Builder(final Builder that) {
        }
        public T source(final UsagePluginApi that) {
            return (T) this;
        }
        protected Builder validate() {
          return this;
        }
        public UsagePluginApiImp build() {
            return new UsagePluginApiImp(this.validate());
        }
    }
}
