/*
 *  Generated by https://github.com/killbill/api-pojos. Do not edit!
 *
 *  Copyright 2022-2022 The Billing Project, LLC
 *
 *  The Billing Project licenses this file to you under the Apache License,
 *  version 2.0 (the "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 */

package org.killbill.billing.invoice.plugin.api.boilerplate;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.Objects;
import org.joda.time.DateTime;
import org.killbill.billing.invoice.plugin.api.PriorInvoiceResult;
import org.killbill.billing.payment.api.PluginProperty;

@JsonDeserialize( builder = PriorInvoiceResultImp.Builder.class )
public class PriorInvoiceResultImp implements PriorInvoiceResult {

    protected Iterable<PluginProperty> adjustedPluginProperties;
    protected boolean isAborted;
    protected DateTime rescheduleDate;

    public PriorInvoiceResultImp(final PriorInvoiceResultImp that) {
        this.adjustedPluginProperties = that.adjustedPluginProperties;
        this.isAborted = that.isAborted;
        this.rescheduleDate = that.rescheduleDate;
    }
    protected PriorInvoiceResultImp(final PriorInvoiceResultImp.Builder<?> builder) {
        this.adjustedPluginProperties = builder.adjustedPluginProperties;
        this.isAborted = builder.isAborted;
        this.rescheduleDate = builder.rescheduleDate;
    }
    protected PriorInvoiceResultImp() { }
    @Override
    public Iterable<PluginProperty> getAdjustedPluginProperties() {
        return this.adjustedPluginProperties;
    }
    @Override
    @JsonGetter("isAborted")
    public boolean isAborted() {
        return this.isAborted;
    }
    @Override
    public DateTime getRescheduleDate() {
        return this.rescheduleDate;
    }
    @Override
    public boolean equals(final Object o) {
        if ( this == o ) {
            return true;
        }
        if ( ( o == null ) || ( this.getClass() != o.getClass() ) ) {
            return false;
        }
        final PriorInvoiceResultImp that = (PriorInvoiceResultImp) o;
        if( !Objects.equals(this.adjustedPluginProperties, that.adjustedPluginProperties) ) {
            return false;
        }
        if( this.isAborted != that.isAborted ) {
            return false;
        }
        if( ( this.rescheduleDate != null ) ? ( 0 != this.rescheduleDate.compareTo(that.rescheduleDate) ) : ( that.rescheduleDate != null ) ) {
            return false;
        }
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        result = ( 31 * result ) + Objects.hashCode(this.adjustedPluginProperties);
        result = ( 31 * result ) + Objects.hashCode(this.isAborted);
        result = ( 31 * result ) + Objects.hashCode(this.rescheduleDate);
        return result;
    }
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer(this.getClass().getSimpleName());
        sb.append("{");
        sb.append("adjustedPluginProperties=").append(this.adjustedPluginProperties);
        sb.append(", ");
        sb.append("isAborted=").append(this.isAborted);
        sb.append(", ");
        sb.append("rescheduleDate=").append(this.rescheduleDate);
        sb.append("}");
        return sb.toString();
    }

    @SuppressWarnings("unchecked")
    public static class Builder<T extends PriorInvoiceResultImp.Builder<T>> {

        protected Iterable<PluginProperty> adjustedPluginProperties;
        protected boolean isAborted;
        protected DateTime rescheduleDate;

        public Builder() { }
        public Builder(final Builder that) {
            this.adjustedPluginProperties = that.adjustedPluginProperties;
            this.isAborted = that.isAborted;
            this.rescheduleDate = that.rescheduleDate;
        }
        public T withAdjustedPluginProperties(final Iterable<PluginProperty> adjustedPluginProperties) {
            this.adjustedPluginProperties = adjustedPluginProperties;
            return (T) this;
        }
        public T withIsAborted(final boolean isAborted) {
            this.isAborted = isAborted;
            return (T) this;
        }
        public T withRescheduleDate(final DateTime rescheduleDate) {
            this.rescheduleDate = rescheduleDate;
            return (T) this;
        }
        public T source(final PriorInvoiceResult that) {
            this.adjustedPluginProperties = that.getAdjustedPluginProperties();
            this.isAborted = that.isAborted();
            this.rescheduleDate = that.getRescheduleDate();
            return (T) this;
        }
        protected Builder validate() {
          return this;
        }
        public PriorInvoiceResultImp build() {
            return new PriorInvoiceResultImp(this.validate());
        }
    }
}
