/*
 *  Generated by https://github.com/killbill/api-pojos. Do not edit!
 *
 *  Copyright 2022-2022 The Billing Project, LLC
 *
 *  The Billing Project licenses this file to you under the Apache License,
 *  version 2.0 (the "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 */

package org.killbill.billing.osgi.api.boilerplate;

import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.util.StdDateFormat;
import com.fasterxml.jackson.datatype.joda.JodaModule;
import java.io.IOException;
import org.killbill.billing.osgi.api.OSGIKillbill;
import org.testng.Assert;
import org.testng.annotations.Test;


@Test(groups = { "fast" })
public class OSGIKillbillImpTest {
    @Test
    public void anInstanceShouldBeEqualToItself()
    {
      OSGIKillbillImp a = new OSGIKillbillImp.Builder<>().build();
      Assert.assertTrue(a.equals(a));
    }
    @Test
    public void anInstanceShouldBeEqualToItsCopy()
    {
      OSGIKillbillImp a = new OSGIKillbillImp.Builder<>().build();
      OSGIKillbillImp b = new OSGIKillbillImp(a);

      Assert.assertTrue(a.equals(b));
    }
    @Test
    public void twoNewInstancesShouldBeEqual()
    {
      OSGIKillbillImp a = new OSGIKillbillImp.Builder<>().build();
      OSGIKillbillImp b = new OSGIKillbillImp.Builder<>().build();

      Assert.assertTrue(a.equals( b));
    }
    @Test
    public void twoNewInstancesHashcodeShouldBeEqual()
    {
      OSGIKillbillImp a =  new OSGIKillbillImp.Builder<>().build();
      OSGIKillbillImp b =  new OSGIKillbillImp.Builder<>().build();

      Assert.assertTrue(a.hashCode() == b.hashCode());
    }
    @Test
    public void twoNewInstancesStringShouldBeEqual()
    {
      OSGIKillbillImp a =  new OSGIKillbillImp.Builder<>().build();
      OSGIKillbillImp b =  new OSGIKillbillImp.Builder<>().build();

      Assert.assertTrue(a.toString().equals(b.toString()));
    }
    @Test
    public void callIssers()
    {
      OSGIKillbillImp a =  new OSGIKillbillImp.Builder<>().build();

    }
    @Test
    public void callGetters()
    {
      OSGIKillbillImp a =  new OSGIKillbillImp.Builder<>().build();

      a.getAccountUserApi();
      a.getAdminPaymentApi();
      a.getAuditUserApi();
      a.getCatalogUserApi();
      a.getCurrencyConversionApi();
      a.getCustomFieldUserApi();
      a.getEntitlementApi();
      a.getExportUserApi();
      a.getInvoicePaymentApi();
      a.getInvoiceUserApi();
      a.getKillbillNodesApi();
      a.getOverdueApi();
      a.getPaymentApi();
      a.getPluginConfigServiceApi();
      a.getPluginsInfoApi();
      a.getRecordIdApi();
      a.getSecurityApi();
      a.getSubscriptionApi();
      a.getTagUserApi();
      a.getTenantUserApi();
      a.getUsageUserApi();
    }
    @Test
    public void jsonRoundtrip()
      throws IOException,
        JsonParseException,
        JsonProcessingException,
        JsonMappingException
    {
      ObjectMapper mapper = new ObjectMapper();
      mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
      mapper.registerModule(new JodaModule());
      mapper.setDateFormat(new StdDateFormat().withColonInTimeZone(true));
      mapper.findAndRegisterModules();

      OSGIKillbillImp a =  new OSGIKillbillImp.Builder<>().build();
      String s =  mapper.writeValueAsString(a);;
      OSGIKillbill b = mapper.readValue(s, OSGIKillbill.class);

      Assert.assertTrue(a.equals( b));
    }
}
